# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a2ff0ce236be574c94a8a6424db75d3183bc0a8d906ed2e67dcec31acc729fbfc978ab4e51048155633e5ac673814247781ec570c1f3d2055d1a185ffa59de7

test:
  secret_key_base: 5d7b494639239f0da1830c824ac2148222d17ea0fd2d65e1563f565b3cc393fe048c5ec4f2bf56a510043a0db0d8229776edb812ee163cbfc1959c63af40bd05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
